### ISSUE TITLE
[BUG] TypeError: keyValidator._parse is not a function

### ISSUE THREAD

**Issue by iamyuu** [rileytomasek/zodix#12]
using separate zod schema doen't work

```
🚀 ~ action ~ error TypeError: keyValidator._parse is not a function
    at ZodObject._parse (types.js:1188:37)
    at ZodObject._parseSync (types.js:109:29)
    at ZodObject.safeParse (types.js:139:29)
    at ZodObject.parse (types.js:120:29)
    at Object.parseForm (index.js:50:22)
    at async action (main.tsx:25:20)
    at async callLoaderOrAction (router.ts:2530:14)
    at async handleAction (router.ts:981:16)
    at async startNavigation (router.ts:904:26)
    at async Object.navigate (router.ts:784:12)
```

here the repo for reproduce: [zodix-rr-reproduce](https://github.com/iamyuu/zodix-rr-reproduce/blob/main/src/main.tsx#L7-L31)

**Comment by rileytomasek** [comment]
Thanks for the bug report and clean reproduction. I stepped through the code and this line is causing the problem:

```
const finalSchema = schema instanceof ZodType ? schema : z.object(schema);
```

The `instanceof` check is returning false so it's wrapping the schema in `z.object()` and causing the issue. There is already [a test for this](https://github.com/rileytomasek/zodix/blob/master/src/parsers.test.ts#L160) so I think the issue is caused by Vite.

@colinhacks is there a way to check if the schema is a `ZodRawShape` vs a `ZodObject` that is more resilient?

**Comment by iamyuu** [comment]
I think the actually issues is missing something on the zodix package, but I'm not sure what it's missing, because if I'm copy the whole package to my source file it's works

**Comment by rileytomasek** [comment]
That makes sense because the dependency resolution would be less error prone that way.

Regardless, I just tested your repro with the [`v0.3.0` release](https://github.com/rileytomasek/zodix/releases/tag/v0.3.0) and it's working now.

**Comment by iamyuu** [comment]
hey @rileytomasek, when using `parseForm` it works, but I need the error validation and I don't wanna throw when parsing fails, I saw on the docs we can use `parseFormSafe`, but when using that function the error is still there

**Comment by ZeevG** [comment]
I'm running into this issue in my project. Removing the following check seems to fix it
```
const finalSchema = schema instanceof ZodType ? schema : z.object(schema);
```
We're using esbuild so it could be because of that. I haven't dug in too deep but without esbuild it seems to work. It would be good to have a fix or workaround, it's a handy library otherwise.

**Comment by toddheslin** [comment]
This is still a problem for me when testing my remix action using vitest. Using latest `0.4.0`.

@ZeevG's solution works fine but doesn't work if you need to infer from the schema to pass around.

I previously have defined:
```ts
export type SnipFormInput = z.infer<typeof snipFormInput>
export const snipFormInput = z.object({
  // ...
})
```

But because I kept getting this error when running tests, I needed to create an intermediate object.

```ts
export type SnipFormInput = z.infer<typeof snipFormInput>
export const snipFormInputObject = {
  // ...
}
export const snipFormInput = z.object({ ...snipFormInputObject })
```

It's a bit hacky, but it lets me run my tests. It's likely a vite issue but if we find a workaround, we should document it so others don't need spend too much time on it.

**Comment by tatemz** [comment]
I also get this error when passing in a `z.union()` schema

**Comment by rileytomasek** [comment]
@tatemz I was able to reproduce the duplicate `instanceof` issue when debugging this initially. Interestingly, this seems only to happen for Vite and not esbuild or others.

I'm open to PRs if someone finds a way to do that check without using `instanceof`.

**Comment by tatemz** [comment]
> if someone finds a way to do that

If only there was a library that  could help us check if an object matched a certain schema structure 🤔 😆 

Joking aside, from the looks of it, the only thing that part of the cares about is that the object has a `.parse()` method on it that can receive data to parse.

Maybe a typeguard could help?

```
const isZodType = (input: ZodRawShape | ZodTypeAny): input is ZodType => typeof raw.parse === "function"
```

**Comment by sonic-knuckles** [comment]
Could we please re-open this issue. Like @toddheslin, I am also using Vitest and the workaround at the moment seems to be storing the schema shape in a separate variable as mentioned previously.

> ```ts
> export type Schema = z.infer<typeof schema>
> export const schemaInput = {
>   // ...
> }
> export const schema = z.object({ ...schemaInput })
> ```

**Comment by toddheslin** [comment]
I agree, this needs to be reopened. Whilst my little trick worked for simple input objects, similar to @tatemz it breaks down when I have a union (or in my case a discriminated union) type:

```ts
export const formSubmissionInput = z
  .discriminatedUnion('snipMedium', [
    // refactored out into plain objects, hoping it would help
    z.object({ ...formSubmissionInputObjectEmail }),
    z.object({ ...formSubmissionInputObjectSms }),
  ])
  .refine(
    (val) => {
      if (val.snipMedium === 'sms') {
        return validatePhoneNumber({
          country: val.phoneCountry,
          number: val.phoneNumber,
        })
      }
      return true
    },
    () => ({ message: 'Phone number is invalid', path: ['phoneNumber'] })
  )
```

@rileytomasek can we reopen this so it's clear a PR is needed?

**Comment by rileytomasek** [comment]
I'm reopening this in case one of you want to take a shot at a PR. Given that it's actually a Vite issue, I won't be able to prioritize fixing it any time soon.

**Comment by sonic-knuckles** [comment]
PR created here based on @tatemz comments https://github.com/rileytomasek/zodix/pull/32

**Comment by colemars** [comment]
Seeing this with RSBuild/RSPack, not using Vite at all.

**Comment by trullock** [comment]
For future idiots (me), if you miss the `()` off your rule, you also get this error. e.g.:

```
const schema = z.object({
	reason: z.string().optional // () missing
})
```
