### ISSUE TITLE
zx.parseQuery errors in component

### ISSUE THREAD

**Issue by CSFlorin** [rileytomasek/zodix#28]
Trying to parse search parameters from `useSearchParams` in a component but I get 

```
Error: Hydration failed because the initial UI does not match what was rendered on the server.
    at throwOnHydrationMismatch (react-dom.development.js:12507:9)
    at tryToClaimNextHydratableInstance (react-dom.development.js:12535:7)
    at updateHostComponent (react-dom.development.js:19902:5)
    at beginWork (react-dom.development.js:21618:14)
    at beginWork$1 (react-dom.development.js:27426:14)
    at performUnitOfWork (react-dom.development.js:26560:12)
    at workLoopConcurrent (react-dom.development.js:26543:5)
    at renderRootConcurrent (react-dom.development.js:26505:7)
    at performConcurrentWorkOnRoot (react-dom.development.js:25738:38)
    at workLoop (scheduler.development.js:266:34)
```

**Comment by rileytomasek** [comment]
Zodix doesn't render anything so it shouldn't be possible to cause this issue. To debug, you should look at how your rendering is impacted by the changes Zodix causes in your loaders/actions.

**Comment by CSFlorin** [comment]
@rileytomasek here is a repro https://stackblitz.com/edit/node-2rgyo7?file=app/routes/index.tsx

**Comment by rileytomasek** [comment]
Zodix is meant to be used in loaders and actions. That repro is calling zx from the component.
You might want to check out the example app: https://github.com/rileytomasek/zodix/tree/master/examples

**Comment by CSFlorin** [comment]
Yes that is my problem. What is the limitation that prevents it from being used in components?
